[package]
name = "banker"
version = "0.1.0"
authors = ["brankeye <brankeye@gmail.com>"]

[dependencies]
uuid = { version = "0.5", features = ["serde", "v4"] }
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
